# Generated by Django 3.2.7 on 2023-04-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=250, unique=True, verbose_name='Property Title'),
        ),
    ]
